services:

  # app
  web:
    build:
      context: .
      dockerfile: docker/php8/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./:/app

  # mysql
  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    platform: linux/x86_64
    environment:
      MYSQL_DATABASE: "laravel"
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    volumes:
      - ./docker/db:/var/lib/mysql
      - ./docker/mysql/my.conf:/etc/mysql/conf.d/my.cnf

  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: 'mysql'
    ports:
      - '8080:80'